import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../components/beranda/Hero";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portofolio Puspita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="" className="">
        <Hero />
      </div>
    </div>
  );
}
